/* File autogenerated by 'make headers_install' */
#ifndef __ASM_STUB_FCNTL_H
#define __ASM_STUB_FCNTL_H
# if defined __x86_64__
#  include <asm-x86_64/fcntl.h>
# elif defined __i386__
#  include <asm-i386/fcntl.h>
# else
#  warning This machine appears to be neither x86_64 nor i386.
# endif
#endif /* __ASM_STUB_FCNTL_H */
