/* File autogenerated by 'make headers_install' */
#ifndef __ASM_STUB_VM86_H
#define __ASM_STUB_VM86_H
# if defined __x86_64__
#  error asm-x86_64/vm86.h does not exist in the x86_64 architecture
# elif defined __i386__
#  include <asm-i386/vm86.h>
# else
#  warning This machine appears to be neither x86_64 nor i386.
# endif
#endif /* __ASM_STUB_VM86_H */
