/* File autogenerated by 'make headers_install' */
#ifndef __ASM_STUB_VSYSCALL32_H
#define __ASM_STUB_VSYSCALL32_H
# if defined __x86_64__
#  include <asm-x86_64/vsyscall32.h>
# elif defined __i386__
#  error asm-i386/vsyscall32.h does not exist in the i386 architecture
# else
#  warning This machine appears to be neither x86_64 nor i386.
# endif
#endif /* __ASM_STUB_VSYSCALL32_H */
